BASICS

In [14]:
#import
import numpy as np

In [21]:
#creating
a = np.array([1, 2, 3])
print(a)

print('------------')

b = np.array([[1.0, 3.0], [2.0, 4.0]])
print(b)

print('------------')

#Creating array with a specific type
c = np.array([1, 2, 3, 40, 50, 70, 127], dtype='int8')

#3D arrray
d3 = np.array([[[[1,2], [3,4]], [[5,6], [7,8]]]])
print(d3, d3.shape)


[1 2 3]
------------
[[1. 3.]
 [2. 4.]]
------------
[[[[1 2]
   [3 4]]

  [[5 6]
   [7 8]]]] (1, 2, 2, 2)


METADATA

In [17]:
aDim = a.ndim #dimentions
print(f'aDim: {aDim}')
aShape = a.shape #format/shape -> same as lenght of a list
print(f'aShape: {aShape}')
aType = a.dtype #type of itens
print(f'aType: {aType}')
aItemSize = a.itemsize
print(f'aItemSize: {aItemSize}') #size of item in bites
aTotalSize = a.nbytes
print(f'aTotalSize: {aTotalSize}') #total size of bites

print('------------')

bDim = b.ndim #dimentions
print(f'bDim: {bDim}')
bShape = b.shape #format/shape
print(f'bShape: {bShape}')
bType = b.dtype #type of itens
print(f'bType: {bType}')
bItemSize = b.itemsize
print(f'bItemSize: {bItemSize}') #size of item in bites,
bTotalSize = b.nbytes
print(f'bTotalSize: {bTotalSize}') #total size of bites

print('------------')
cType = c.dtype
print(f'cType: {cType}')
cItemSize = c.itemsize
print(f'cItemSize: {cItemSize}')
cTotalSize = c.nbytes
print(f'cTotalSize: {cTotalSize}') #total size of bites

aDim: 1
aShape: (3,)
aType: int32
aItemSize: 4
aTotalSize: 12
------------
bDim: 2
bShape: (2, 2)
bType: float64
bItemSize: 8
bTotalSize: 32
------------
cType: int8
cItemSize: 1
cTotalSize: 7
