In [7]:
import numpy as np

Using zeros and ones

In [ ]:
#numbers are created with float data
a = np.zeros(3)
print(f'a: {a}')

print('-----')

b = np.zeros([3,5])
print(f'b: {b}')

print('-----')

c = np.zeros([2,3,5])
print(f'c: {c}')

a: [0. 0. 0.]
-----
b: [[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]
-----
c: [[[0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]]

 [[0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]]]


In [ ]:
#numbers are created with int data using dtype param
a = np.ones(3, dtype='int32')
print(f'a: {a}')

print('-----')

b = np.ones([3,5], dtype='int32')
print(f'b: {b}')

print('-----')

c = np.ones([2,3,5], dtype='int32')
print(f'c: {c}')

a: [1 1 1]
-----
b: [[1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]]
-----
c: [[[1 1 1 1 1]
  [1 1 1 1 1]
  [1 1 1 1 1]]

 [[1 1 1 1 1]
  [1 1 1 1 1]
  [1 1 1 1 1]]]


In [14]:
#we can use np full to create a matrices
a = np.full([3,2], 99)
print(f'a: {a}')

print('-----')

#using full like to create the same "shape" with another value
b = np.full_like(a, 25)
print(f'b: {b}')



a: [[99 99]
 [99 99]
 [99 99]]
-----
b: [[25 25]
 [25 25]
 [25 25]]


In [ ]:
#creating random matrices
c = np.random.rand(2, 2, 3) #2 matrices with 2 lines and 3 columns
print(f'c: {c}')

print('-----')

#creating random matrice with specific type
d = np.random.randint(0, 10, size=(2,3,5)) #2 matrices with 2 lines and 5 columns with numbers until 10(max) - We can have a min value
print(f'd: {d}')

c: [[[0.25759163 0.54140703 0.59846245]
  [0.28959929 0.98824162 0.82304087]]

 [[0.41615719 0.46897474 0.82934011]
  [0.80420369 0.62385798 0.3919338 ]]]
-----
d: [[[4 6 4 8 2]
  [1 6 0 7 4]
  [9 2 3 9 0]]

 [[2 2 8 3 7]
  [5 2 2 0 2]
  [5 0 7 1 0]]]


In [20]:
#identity matrice -> square root
a = np.identity(9)
print(f'a: {a}')

a: [[1. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 1.]]
